config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  resources :pages do
    put '/like', to: 'pages#like', on: :member
    put '/dislike', to: 'pages#dislike', on: :member
  end

  get 'authors', to: 'pages#authors', as: :authors
  delete 'author/:name', to: 'pages#delete_author', as: :delete_author
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  title      :string
#  subtitle   :string
#  content    :text
#  likes      :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Page < ApplicationRecord
  validates :title, presence: true
  validates :subtitle, presence: true
  validates :content, presence: true

  def publication_date
    created_at.strftime('%D')
  end

  def like
    self.likes += 1
  end

  def dislike
    unless self.likes == 0
      self.likes -= 1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(1)
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(params.require(:page).permit(:title, :subtitle, :author, :content))
    @page.save
  end

  def update
    @page = Page.find(params[:id])
    @page.update(params.require(:page).permit(:title, :subtitle, :author, :content))
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
  end

  def like
    @page = Page.find(params[:id])
  end

  def dislike
    @page = Page.find(params[:id])
  end

  def authors
    @authors = Page.distinct.pluck(:author)
    @authors.delete('Unknown')
  end

  def delete_author
    author = params[:name]
    pages = Page.where(author: author)
    pages.each do |page|
      page.update!(author: 'Unknown')
    end
    redirect_to authors_path, notice: "#{author} posts were set to Unknown"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when "notice" then "alert alert-info alert-dismissible fade show"
        when "success" then "alert alert-success alert-dismissible fade show"
        when "error" then "alert alert-danger alert-dismissible fade show"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: flash_class(key), role: "alert"}
    = value
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand.navbar-light.bg-light
  = link_to 'Pages', root_path, class: 'navbar-brand'
  %button.navbar-toggler{type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      %li.navbar-item
        = link_to 'Pages', pages_path, class: "nav-link"
      %li.navbar-item
        = link_to 'Authors', authors_path, class: "nav-link"
  = link_to 'New page', new_page_path, class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Controladores
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container-fluid
      = render 'layouts/flash_messages'
      = yield

app/views/pages/_form.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    .alert.alert-danger.alert-dismissible.fade.show
      %h2= "#{pluralize(@page.errors.count, "error")}:"
      %ul
        - @page.errors.full_messages.each do |message|
          %li= message
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} &times;

  .form-group
    = f.text_field :title, placeholder: :title, class: 'form-control', autocomplete: 'off'
  .form-group
    = f.text_field :subtitle, placeholder: :subtitle, class: 'form-control', autocomplete: 'off'
  .form-group
    = f.text_field :author, placeholder: :author, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', pages_path, class: 'btn btn-danger'

app/views/pages/authors.html.haml
%h1.text-center.mb-4.mt-4 Page authors
- if @authors.empty?
  .alert.alert-info There are no authors
- else
  .row
    .col-12.col-md-6.offset-md-3
      .list-group
        - @authors.each do |author|
          .list-group-item.list-group-item-action.d-flex.justify-content-between.align-items-center
            = link_to author, pages_path(author: author)
            = link_to delete_author_path(author), method: 'delete', class: 'btn btn-danger', data: { confirm: 'Are you sure?'} do
              = icon 'fas', 'trash-alt'

app/views/pages/create.html.haml
- if @page.errors.any?
  .alert.alert-danger
    %h2= "#{pluralize(@page.errors.count, "error")}:"
    %ul
      - @page.errors.full_messages.each do |message|
        %li= message
    = link_to 'Try again', new_page_path
- else
  .alert.alert-info
    The page was successfully created
    = link_to 'See page', @page

app/views/pages/destroy.html.haml
.alert.alert-info
  The page was successfully destroyed
  = link_to 'See pages list', pages_path

app/views/pages/dislike.html.haml
.alert.alert-info
  Page was disliked. You're supposed to redirect this to show
  = link_to 'Go to show', @page

app/views/pages/edit.html.haml
%h1.text-center.mb-4.mt-4 Edit page
.row
  .col-12.col-md-6.offset-md-3
    = render 'form'

app/views/pages/index.html.haml
%h1.text-center.mb-4.mt-4
  - if @author.blank?
    All pages
  - else
    Pages by
    = @author

- if @pages.empty?
  .alert.alert-info There are no pages
- else
  .row
    - @pages.each do |page|
      .card.col-12.col-md-4
        .card-body
          = link_to pages_path(author: page.author), class: 'card-link' do
            %p.small.text-muted.text-right=page.author
          %h2.card-title=page.title
          .card-subtitle.mb-2.text-muted=page.subtitle
          .card-text=page.content.truncate_words(50)
          .d-flex.justify-content-between.align-items-center.mt-3
            = link_to 'Read more', page, class: 'card-link'
            .buttons
              = link_to page, method: 'delete', class: 'btn btn-danger mr-3', data: { confirm: 'Are you sure?'} do
                = icon 'fas', 'trash-alt'
              = link_to edit_page_path(page), class: 'btn btn-primary mr-3' do
                = icon 'fas', 'edit'
              = link_to like_page_path(page), method: 'put', class: 'btn btn-success' do
                = icon 'fas', 'heart'
                = page.likes

app/views/pages/like.html.haml
.alert.alert-info
  Page was liked. You're supposed to redirect this to show
  = link_to 'Go to show', @page

app/views/pages/new.html.haml
%h1.text-center.mb-4.mt-4 New page
.row
  .col-12.col-md-6.offset-md-3
    = render 'form'

app/views/pages/show.html.haml
%h1.text-center.mt-4=@page.title
.text-muted.text-center.mb-4=@page.subtitle
.row.mb-4
  .col-12.col-md-6.offset-md-1
    .small.text-muted.text-center
      = "Published by #{@page.author} on #{@page.publication_date}"
    .text-justify{style: "text-indent: 10%"}=@page.content
  .col-12.col-md-4
    %h3 Actions
    = link_to pages_path, class: 'btn btn-dark mr-3' do
      = icon 'fas', 'arrow-left'
    = link_to @page, method: 'delete', class: 'btn btn-danger mr-3', data: { confirm: 'Are you sure?'} do
      = icon 'fas', 'trash-alt'
    = link_to edit_page_path(@page), class: 'btn btn-primary mr-3' do
      = icon 'fas', 'edit'
    = link_to like_page_path(@page), method: 'put', class: 'btn btn-success mr-3' do
      = icon 'fas', 'heart'
      = @page.likes
    = link_to dislike_page_path(@page), method: 'put', class: 'btn btn-secondary' do
      = icon 'fas', 'heart-broken'

app/views/pages/update.html.haml
- if @page.errors.any?
  .alert.alert-danger
    %h2= "#{pluralize(@page.errors.count, "error")}:"
    %ul
      - @page.errors.full_messages.each do |message|
        %li= message
    = link_to 'Try again', edit_page_path(@page)
- else
  .alert.alert-info
    The page was successfully updated
    = link_to 'See page', @page